name: Build CSS with Tailwind

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Commit and push compiled CSS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/output.css
          git commit -m "Build Tailwind CSS [auto]" || echo "No changes to commit"
          git push
