name: Procesar imágenes Tesla

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 1 * *'  # Ejecuta el día 1 de cada mes a las 6:00 UTC

jobs:
  procesar-imagenes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y libavif-bin
        pip install requests Pillow

    - name: Ejecutar script de procesamiento
      env:
        REMOVE_BG_API_KEY: ${{ secrets.REMOVE_BG_API_KEY }}
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      run: python scripts/procesar_imagenes.py

    - name: Commit cambios procesados
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git add assets-editados/* || true
        git diff --cached --quiet || (git commit -m "Imágenes Tesla procesadas automáticamente" && git push)
