name: Scraping Tesla Mensual

on:
  schedule:
    - cron: '0 0 1 * *'  # Ejecutar el d칤a 1 de cada mes a las 00:00 UTC
  workflow_dispatch:     # Permite ejecuci칩n manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install requests-html lxml_html_clean

      - name: Ejecutar scraping
        run: python scripts/scrapear_tesla.py

      - name: Commit im치genes nuevas
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add assets
          git commit -m "游닞 Nuevas im치genes Tesla descargadas autom치ticamente" || echo "Sin cambios"
          git push
